apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lfc3
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0069-tenant/tkrw-pr712-0075-0069-app/devfile-sample-lfc3@sha256:ab2a9d41bcbf6aeb71bdb27e71fece89bdbde2c25117f61a0a50efe12b039273
        name: my-nodejs
        resources: {}
status: {}
